language: ruby
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.5
  - 2.3.6
  - 2.4.2
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/activerecord-4.2
  - gemfiles/activerecord-5.0
  - gemfiles/activerecord-5.1
  - gemfiles/activerecord-5.2
